# Generated by Django 3.0 on 2021-11-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Coordinate')),
            ],
        ),
    ]
