# Generated by Django 3.0 on 2021-11-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Place'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField()),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Place')),
            ],
        ),
    ]
