# Generated by Django 3.0 on 2021-11-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211128_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='lang',
            new_name='long',
        ),
    ]
