# Generated by Django 3.0 on 2021-11-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_images_image_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
